### ISSUE TITLE
Line 105 - missing %d

### ISSUE THREAD

**Issue by MDAR** [m5stack/M5-STHS34PF80#2]
### Describe the bug

One character missing in Line 105, which prevents the value being displayed in the Serial Monitor / Plotter

Line 105 currently - `Serial.printf("Prescence Detected!  PrescenceValue:%\n", presenceVal);  `

Should be - `Serial.printf("Prescence Detected!  PrescenceValue:%d\n", presenceVal );`

### To reproduce

run the code as is, with tweaks for platform in use

### Expected behavior

plotter to show both Pres and Motion values

### Environment

any

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5-STHS34PF80/issues?q=)
- [X] My report contains all necessary details

**Comment by TinyuZhao** [comment]
You can submit a PR to fix it, Thank you.

**Comment by MDAR** [comment]
@Tinyu-Zhao 
I'd love to do I that, but I have no idea how GitHub works. (and I don't have time to learn it to be completely honest, as it's not something I use on a monthly basis, let alone as an everyday tool)
I did try this morning, but I just got lost and confused.

Nor do I know how you (M5Stack) like to layout your repositories

**Comment by TinyuZhao** [comment]
Thanks for the discovery, I've updated it.
